### ISSUE TITLE
Tutorial on using this package

### ISSUE THREAD

**Issue by broall** [pluralsight/irt_parameter_estimation#1]
Hi, 

Is there any document that guides users how to use this package? I don't know how to implement this package.

Thanks in advance.

**Comment by nisalikularatne** [comment]
Hi,

Is there any document that guides users how to use this package? I don't know how to implement this package. Would sincerely like to see how this package works

Thanks in advance.

**Comment by victorhwfreire** [comment]
Hi,

Is there any document that guides users how to use this package? I don't know how to implement this package. Would sincerely like to see how this package works

Thanks in advance.

**Comment by jisaaco** [comment]
Hi,

Is there any document that guides users how to use this package? I don't know how to implement this package. Would sincerely like to see how this package works

Thanks in advance.

**Comment by bjcCin** [comment]
Hi,

Is there any document that guides users how to use this package? I don't know how to implement this package. Would sincerely like to see how this package works

Thanks in advance.

**Comment by EverAPC** [comment]
Hi, 
Has anyone found an implementation of this package? If so kindly let me know
Thank You

**Comment by ichko** [comment]
Tutorial PLS

**Comment by davidmashburn** [comment]
@broall @nisalikularatne @EverAPC @ichko Thanks for your interest in our package. Apologies for the (extremely) late response to your request, but here it is. Hope it helps :)
https://github.com/pluralsight/irt_parameter_estimation/blob/master/doc/QuickTutorial.ipynb

**Comment by ichko** [comment]
Thanks!
